# Generated by Django 3.1.5 on 2021-01-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0004_auto_20210130_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
    ]
